# Generated by Django 5.2.1 on 2025-06-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_voices_alter_question_voice_delete_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='percent',
            field=models.IntegerField(default=0),
        ),
    ]
